#!/bin/bash

set -ex

cd "$(dirname "$0")"

./projfs image fuse3

./projfs image develop
./projfs develop configure
./projfs develop make
./projfs develop test || (
	cat ../t/test-suite.log;
	exit 1
)

./projfs image vfs
./projfs vfs restore
./projfs vfs make

./projfs image integrate
./projfs integrate clone
./projfs test --force
