FROM debian:stretch

LABEL org.label-schema.name="projfs-fuse3"
LABEL org.label-schema.description="projfs Linux libfuse v3 image"
LABEL org.label-schema.vendor="GitHub"
LABEL org.label-schema.schema-version="1.0"

RUN \
	echo 'deb http://deb.debian.org/debian stretch-backports main' >> /etc/apt/sources.list.d/stretch-backports.list && \
	apt-get update -qq && \
	apt-get install -y -qq --no-install-recommends build-essential ca-certificates pkg-config wget udev && \
	apt-get install -y -qq --no-install-recommends -t=stretch-backports meson && \
	rm -rf /var/lib/apt/lists/*

ARG FUSE_NWO=kivikakk/libfuse
ARG FUSE_VERSION=3.4.1-kivikakk-userdata1
ARG FUSE_SHA256=9b3ee6ea4cf280b038836fc99bb38f18ed7499e982f60501782175323c15a553

WORKDIR /tmp

# fuse3 requires meson 0.42, available from stretch-backports
# wget depends on ca-certificates

ENV FUSE_RELEASE "fuse-$FUSE_VERSION"
ENV FUSE_DOWNLOAD "$FUSE_RELEASE.tar.xz"
ENV FUSE_URL_PATH "releases/download/$FUSE_RELEASE/$FUSE_DOWNLOAD"

RUN \
	wget -q "https://github.com/$FUSE_NWO/$FUSE_URL_PATH" && \
	echo "$FUSE_SHA256 $FUSE_DOWNLOAD" | sha256sum -c -

RUN tar -xJf "$FUSE_DOWNLOAD"
WORKDIR "$FUSE_RELEASE/build"

RUN meson --prefix=/usr --sysconfdir=/etc --localstatedir=/var ..
RUN ninja -j "$(nproc)"
RUN ninja install
