#!/usr/bin/env ruby
#
# Linux Projected Filesystem
# Copyright (C) 2019 GitHub, Inc.
#
# See the COPYING file distributed with this library for additional
# information regarding copyright ownership.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library, in the file LICENSE.md; if not,
# see <http://www.gnu.org/licenses/>.

require 'commonmarker'

doc = CommonMarker.render_doc(File.read('README.md'))

did_replace = false

doc.walk do |node|
  if !did_replace && node.type == :code_block && node.string_content.start_with?("$ ./projfs")
    node.string_content = "$ ./projfs\n" + `./projfs 2>&1`
    did_replace = true
  end
end

raise "replaced nothing" unless did_replace

File.open("README.md", "w") {|f| f.write(doc.to_commonmark)}
